

dfs:
  url: 94.191.83.120:8181
fdfs:
  connectTimeout: 600
  soTimeout: 1500
  thumbImage:
    height: 150
    width: 150
  trackerList:
    - 94.191.83.120:12050


spring:
  redis:
    host: 94.191.83.120
    port: 6379
    password: 123456
  #  data:
  #    mongodb:
  #      uri: mongodb://94.191.83.120:27017/mall   #114.115.171.119
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  application:
    name: mall-account
shiro:
  maxAge:
    day: 10
company:
  images:
    login-logo:
    logo:
    login-bg:
wx:
  appid: wxc5eae5bf209e986f
  appsecret:
  redirect_uri:

goods:
  pic:
    domain: http://demo5.tp-shop.cn


eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8763/eureka/
    register-with-eureka: true
    fetch-registry: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 5000
  OkToRetryOnAllOperations: false
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
